import { Scene, Timer, Color, Group, Mesh, Bone } from "three";
import {
  WebGLRenderer,
  WebGLRenderTarget,
  SRGBColorSpace,
  LinearSRGBColorSpace,
  LinearFilter,
  NearestFilter,
  RGBAFormat,
  RedFormat,
} from "three";
import { CubeCamera, PerspectiveCamera, OrthographicCamera } from "three";
import { Texture, DataTexture, TextureLoader, CubeTextureLoader } from "three";
import {
  NoToneMapping,
  LinearToneMapping,
  ReinhardToneMapping,
  CineonToneMapping,
  ACESFilmicToneMapping,
} from "three";
import {
  DirectionalLight,
  DirectionalLightHelper,
  AmbientLight,
  PointLight,
  PointLightHelper,
} from "three";
import { Points, Vector2, Vector3, Quaternion } from "three";
import {
  AnimationMixer,
  LoopOnce,
  LoopPingPong,
  LoopRepeat,
  AnimationAction,
  AnimationClip,
  AnimationUtils,
} from "three";
import {
  Material,
  MeshBasicMaterial,
  MeshToonMaterial,
  MeshLambertMaterial,
  MeshPhongMaterial,
  MeshStandardMaterial,
  MeshMatcapMaterial,
  MeshPhysicalMaterial,
  ShaderMaterial,
} from "three";
import {
  BackSide,
  FrontSide,
  DoubleSide,
  NeverDepth,
  AlwaysDepth,
  LessDepth,
  LessEqualDepth,
  EqualDepth,
  GreaterEqualDepth,
  GreaterDepth,
  NotEqualDepth,
} from "three";
import {
  NoBlending,
  NormalBlending,
  AdditiveBlending,
  SubtractiveBlending,
  MultiplyBlending,
  CustomBlending,
  MaterialBlending,
} from "three";
import {
  BufferAttribute,
  KeyframeTrack,
  VectorKeyframeTrack,
  QuaternionKeyframeTrack,
} from "three";

export const THREE = {
  Scene,
  Timer,
  Color,
  Group,
  Mesh,
  Bone,
  WebGLRenderer,
  WebGLRenderTarget,
  SRGBColorSpace,
  LinearSRGBColorSpace,
  LinearFilter,
  NearestFilter,
  RGBAFormat,
  RedFormat,
  CubeCamera,
  PerspectiveCamera,
  OrthographicCamera,
  Texture,
  DataTexture,
  TextureLoader,
  CubeTextureLoader,
  NoToneMapping,
  LinearToneMapping,
  ReinhardToneMapping,
  CineonToneMapping,
  ACESFilmicToneMapping,
  DirectionalLight,
  DirectionalLightHelper,
  AmbientLight,
  PointLight,
  PointLightHelper,
  Points,
  Vector2,
  Vector3,
  Quaternion,
  AnimationMixer,
  LoopOnce,
  LoopPingPong,
  LoopRepeat,
  AnimationAction,
  AnimationClip,
  AnimationUtils,
  Material,
  MeshBasicMaterial,
  MeshToonMaterial,
  MeshLambertMaterial,
  MeshPhongMaterial,
  MeshStandardMaterial,
  MeshMatcapMaterial,
  MeshPhysicalMaterial,
  ShaderMaterial,
  BackSide,
  FrontSide,
  DoubleSide,
  NeverDepth,
  AlwaysDepth,
  LessDepth,
  LessEqualDepth,
  EqualDepth,
  GreaterEqualDepth,
  GreaterDepth,
  NotEqualDepth,
  NoBlending,
  NormalBlending,
  AdditiveBlending,
  SubtractiveBlending,
  MultiplyBlending,
  CustomBlending,
  MaterialBlending,
  BufferAttribute,
  KeyframeTrack,
  VectorKeyframeTrack,
  QuaternionKeyframeTrack,
};
